(set-terminal! "st")
(set-font! "Iosevka Nerd Font Propo:style=Bold:size=14")

(border-width! 2)
(border-focused! #x6dade3)
(border-unfocused! #x444444)

(gaps-inner! 5 5)
(gaps-outer! 5 5)

(bind '(mod1) "Return" (spawn-terminal))
(bind '(mod1) "d" (spawn "rofi -show drun"))
(bind '(mod1) "s" (spawn "maim -s | xclip -selection clipboard -t image/png"))
(bind '(mod1) "q" (kill-client))
(bind '(mod1 shift) "q" (quit))
(bind '(mod1 shift) "r" (reload-config))

(bind '(mod1) "j" (focus-next))
(bind '(mod1) "k" (focus-prev))
(bind '(mod1 shift) "j" (move-next))
(bind '(mod1 shift) "k" (move-prev))

(bind '(mod1) "h" (resize-master -50))
(bind '(mod1) "l" (resize-master 50))
(bind '(mod1) "i" (inc-master))
(bind '(mod1) "p" (dec-master))

(bind '(mod1) "a" (toggle-gaps))
(bind '(mod1) "f" (toggle-fullscreen))
(bind '(mod1) "Space" (toggle-floating))

(bind '(mod1) "comma" (focus-monitor -1))
(bind '(mod1) "period" (focus-monitor 1))
(bind '(mod1 shift) "comma" (send-to-monitor -1))
(bind '(mod1 shift) "period" (send-to-monitor 1))

(bind '(mod1) "1" (view-tag 0))
(bind '(mod1) "2" (view-tag 1))
(bind '(mod1) "3" (view-tag 2))
(bind '(mod1) "4" (view-tag 3))
(bind '(mod1) "5" (view-tag 4))
(bind '(mod1) "6" (view-tag 5))
(bind '(mod1) "7" (view-tag 6))
(bind '(mod1) "8" (view-tag 7))
(bind '(mod1) "9" (view-tag 8))

(bind '(mod1 shift) "1" (move-to-tag 0))
(bind '(mod1 shift) "2" (move-to-tag 1))
(bind '(mod1 shift) "3" (move-to-tag 2))
(bind '(mod1 shift) "4" (move-to-tag 3))
(bind '(mod1 shift) "5" (move-to-tag 4))
(bind '(mod1 shift) "6" (move-to-tag 5))
(bind '(mod1 shift) "7" (move-to-tag 6))
(bind '(mod1 shift) "8" (move-to-tag 7))
(bind '(mod1 shift) "9" (move-to-tag 8))

(bind '(mod1 control) "1" (toggle-view-tag 0))
(bind '(mod1 control) "2" (toggle-view-tag 1))
(bind '(mod1 control) "3" (toggle-view-tag 2))
(bind '(mod1 control) "4" (toggle-view-tag 3))
(bind '(mod1 control) "5" (toggle-view-tag 4))
(bind '(mod1 control) "6" (toggle-view-tag 5))
(bind '(mod1 control) "7" (toggle-view-tag 6))
(bind '(mod1 control) "8" (toggle-view-tag 7))
(bind '(mod1 control) "9" (toggle-view-tag 8))

(bind '(mod1 control shift) "1" (toggle-tag 0))
(bind '(mod1 control shift) "2" (toggle-tag 1))
(bind '(mod1 control shift) "3" (toggle-tag 2))
(bind '(mod1 control shift) "4" (toggle-tag 3))
(bind '(mod1 control shift) "5" (toggle-tag 4))
(bind '(mod1 control shift) "6" (toggle-tag 5))
(bind '(mod1 control shift) "7" (toggle-tag 6))
(bind '(mod1 control shift) "8" (toggle-tag 7))
(bind '(mod1 control shift) "9" (toggle-tag 8))

(rule '((class . "Gimp") (floating . #t)))
(rule '((class . "Firefox") (tag . 8)))
