(set-terminal! "alacritty")
(set-font! "Iosevka Nerd Font Propo:style=Bold:size=14")
(set-tags! '("1", "2", "3", "4", "5", "6", "7", "8", "9"))
; (set-tags! '("", "󰊯", "", "", "󰙯", "󱇤", "", "󱘶", "󰧮"))

;; colors
(define red "#f7768e")
(define cyan "#0db9d7")
(define green "#9ece6a")
(define light-blue "#7aa2f7")
(define blue "#6dade3")
(define purple "#ad8ee6")
(define grey "#bbbbbb")
(define separator "#444b6a")

(border-width! 2)
(border-focused! blue)
(border-unfocused! grey)

(gaps-inner! 5 5)
(gaps-outer! 5 5)

;; bar blocks (right side, rendered right-to-left)
;; syntax: (block-xxx ... color)        = underline on (default)
;;         (block-xxx ... color #f)     = underline off
(block-shell " {}" "/home/tony/.config/oxwm/bad_script.sh" 5 green)
(block-static "│" separator #f)
(block-ram " Ram: {}/{} GB" 5 light-blue)
(block-static "│" separator #f)
(block-shell " {}" "uname -r" 99999 red)
(block-static "│" separator #f)
(block-battery "⚡ Bat: {}%" "- Bat: {}%" "✓ Bat: {}%" "BAT0" 30 purple)
(block-static "│" separator #f)
(block-datetime "󰸗 {}" "%a, %b %d - %-I:%M %P" 1 cyan)

(bind '(mod4) "Return" (spawn-terminal))
(bind '(mod4) "d" (spawn "rofi -show drun"))
(bind '(mod4) "s" (spawn "maim -s | xclip -selection clipboard -t image/png"))
(bind '(mod4) "q" (kill-client))
(bind '(mod4 shift) "q" (quit))
(bind '(mod4 shift) "r" (reload-config))

(bind '(mod4) "j" (focus-next))
(bind '(mod4) "k" (focus-prev))
(bind '(mod4 shift) "j" (move-next))
(bind '(mod4 shift) "k" (move-prev))

(bind '(mod4) "h" (resize-master -50))
(bind '(mod4) "l" (resize-master 50))
(bind '(mod4) "i" (inc-master))
(bind '(mod4) "p" (dec-master))

(bind '(mod4) "a" (toggle-gaps))
(bind '(mod4) "f" (toggle-fullscreen))
(bind '(mod4) "Space" (toggle-floating))

(bind '(mod4) "comma" (focus-monitor -1))
(bind '(mod4) "period" (focus-monitor 1))
(bind '(mod4 shift) "comma" (send-to-monitor -1))
(bind '(mod4 shift) "period" (send-to-monitor 1))

(bind '(mod4) "1" (view-tag 0))
(bind '(mod4) "2" (view-tag 1))
(bind '(mod4) "3" (view-tag 2))
(bind '(mod4) "4" (view-tag 3))
(bind '(mod4) "5" (view-tag 4))
(bind '(mod4) "6" (view-tag 5))
(bind '(mod4) "7" (view-tag 6))
(bind '(mod4) "8" (view-tag 7))
(bind '(mod4) "9" (view-tag 8))

(bind '(mod4 shift) "1" (move-to-tag 0))
(bind '(mod4 shift) "2" (move-to-tag 1))
(bind '(mod4 shift) "3" (move-to-tag 2))
(bind '(mod4 shift) "4" (move-to-tag 3))
(bind '(mod4 shift) "5" (move-to-tag 4))
(bind '(mod4 shift) "6" (move-to-tag 5))
(bind '(mod4 shift) "7" (move-to-tag 6))
(bind '(mod4 shift) "8" (move-to-tag 7))
(bind '(mod4 shift) "9" (move-to-tag 8))

(bind '(mod4 control) "1" (toggle-view-tag 0))
(bind '(mod4 control) "2" (toggle-view-tag 1))
(bind '(mod4 control) "3" (toggle-view-tag 2))
(bind '(mod4 control) "4" (toggle-view-tag 3))
(bind '(mod4 control) "5" (toggle-view-tag 4))
(bind '(mod4 control) "6" (toggle-view-tag 5))
(bind '(mod4 control) "7" (toggle-view-tag 6))
(bind '(mod4 control) "8" (toggle-view-tag 7))
(bind '(mod4 control) "9" (toggle-view-tag 8))

(bind '(mod4 control shift) "1" (toggle-tag 0))
(bind '(mod4 control shift) "2" (toggle-tag 1))
(bind '(mod4 control shift) "3" (toggle-tag 2))
(bind '(mod4 control shift) "4" (toggle-tag 3))
(bind '(mod4 control shift) "5" (toggle-tag 4))
(bind '(mod4 control shift) "6" (toggle-tag 5))
(bind '(mod4 control shift) "7" (toggle-tag 6))
(bind '(mod4 control shift) "8" (toggle-tag 7))
(bind '(mod4 control shift) "9" (toggle-tag 8))

(rule '((class . "Gimp") (floating . #t)))
(rule '((class . "Firefox") (tag . 8)))
